import React, { useState, useEffect } from 'react';
import { View, Text, ScrollView, ActivityIndicator } from 'react-native';
import { ref, query, orderByChild, equalTo, onValue, off } from 'firebase/database';
import { database } from 'helpers/firebaseHelper';
import OutfitCard from 'components/scan/OutfitCard';
import CustomHeader from 'components/global/CustomHeader';
import ProductCard from 'components/global/ProductCard';
import { useScan } from '../ScanContexs';
import { getScanResult, ScanResultData, ScanProduct } from 'services/scanApi';
import { Linking } from 'react-native';

interface Step4Props {
  onBack?: () => void;
}

export default function Step4({ onBack }: Step4Props) {
  const { formData } = useScan();
  const ticketId = formData.ticketId;

  const [scanResult, setScanResult] = useState<ScanResultData | null>(null);
  const [products, setProducts] = useState<ScanProduct[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // Ambil summary + img_urls dari BE
  useEffect(() => {
    if (!ticketId) return;

    getScanResult(ticketId)
      .then(data => setScanResult(data))
      .catch(err => console.log('Error getScanResult:', err))
      .finally(() => setIsLoading(false));
  }, [ticketId]);

  // Ambil products dari Firebase
  useEffect(() => {
    if (!ticketId) return;

    const ticketRef = query(
      ref(database, 'ticket-request'),
      orderByChild('ticket_id'),
      equalTo(ticketId)
    );

    const unsubscribe = onValue(ticketRef, (snapshot) => {
      if (!snapshot.exists()) return;

      const raw = snapshot.val();
      const entries = Object.values(raw) as any[];
      const ticket = entries.find((e: any) => e.ticket_id === ticketId);

      if (ticket?.data) {
        const productList: ScanProduct[] = Object.values(ticket.data);
        setProducts(productList);
      }
    });

    return () => off(ticketRef);
  }, [ticketId]);

  const parsePrice = (priceStr: string): number => {
    return parseInt(priceStr.replace(/[^0-9]/g, '')) || 0;
  };

  const parseRating = (ratingStr: string): number => {
    return parseFloat(ratingStr) || 0;
  };

  const parseBuyerCount = (buyStr: string): number => {
    const match = buyStr.match(/(\d+)/);
    return match ? parseInt(match[1]) * (buyStr.includes('rb') ? 1000 : 1) : 0;
  };

  if (isLoading) {
    return (
      <View className="flex-1 bg-gray-100 items-center justify-center">
        <ActivityIndicator size="large" color="#8F42DE" />
        <Text className="text-gray-500 mt-3">Loading your outfit...</Text>
      </View>
    );
  }

  return (
    <View className="flex-1 bg-gray-100">
      <CustomHeader
        title="Your Outfit"
        subtitle={scanResult?.title ?? 'Generated look'}
        showBackButton
        onBackPress={onBack}
      />

      <ScrollView className="flex-1">
        <View className="px-6 pt-2">
          <OutfitCard
            title={scanResult?.title ?? ''}
            subtitle="Generated by Stylo AI"
            description={scanResult?.summary ?? ''}
            images={scanResult?.img_urls ?? []}
            onSaveOutfit={() => console.log('Save outfit')}
            onSaveItems={() => console.log('Save single items')}
          />
        </View>

        {products.length > 0 && (
          <View className="px-6">
            <Text className="text-lg font-semibold mb-1">
              Shoppable pieces
            </Text>
            <Text className="text-sm text-gray-500 mb-4">
              Matched to your size & style.
            </Text>

            {products.map((product, index) => (
              <ProductCard
                key={index}
                imageUrl={product.img_url}
                title={product.name}
                rating={parseRating(product.rating)}
                price={parsePrice(product.price)}
                buyerCount={parseBuyerCount(product.total_buy)}
                onPressProduct={() => Linking.openURL(product.link_url)}
              />
            ))}
          </View>
        )}

        <View className="h-28" />
      </ScrollView>
    </View>
  );
}