import React, { useState } from 'react';
import {View, Text, ScrollView, TouchableOpacity, Image,} from 'react-native';
import OutfitCard from 'components/scan/OutfitCard';
import CustomHeader from 'components/global/CustomHeader';
import ProductCard from 'components/global/ProductCard';

interface Step4Props {
  onBack?: () => void;
}

export default function Step4({
  onBack,

}: Step4Props) {

  const handleProductPress = () => {
    console.log('Product pressed');
  };

  return (
    <View className="flex-1 bg-gray-100">
      <CustomHeader
        title="Your Outfit"
        subtitle="Dinner Date."
        showBackButton
        onBackPress={onBack}
        />

      <ScrollView className="flex-1">

        <View className="px-6 pt-2">
          <OutfitCard
            title="Soft neutral date night look"
            subtitle="Generated by Style AI · Look 1 of 5"
            description="Cream knit top with tailored black trousers, layered with a light trench and clean white sneakers. Balanced, polished, and comfortable for an indoor dinner date."
            onSaveOutfit={() => {
              console.log('Save outfit');
            }}
            onSaveItems={() => {
              console.log('Save single items');
            }}
          />
        </View>

        <View className="px-6">
          <Text className="text-lg font-semibold mb-1">
            Shoppable pieces
          </Text>
          <Text className="text-sm text-gray-500 mb-4">
            Picked from Shopee · Matched to your size & style.
          </Text>

          <ProductCard
            imageUrl="https://example.com/product.jpg"
            title="Cream ribbed knit long-sleeve top"
            rating={4.8}
            price={189000}
            buyerCount={1200}
            onPressProduct={handleProductPress}
          />  

          <ProductCard
            imageUrl="https://example.com/product.jpg"
            title="Cream ribbed knit long-sleeve top"
            rating={4.8}
            price={189000}
            buyerCount={1200}
            onPressProduct={handleProductPress}
          /> 

          <ProductCard
            imageUrl="https://example.com/product.jpg"
            title="Cream ribbed knit long-sleeve top"
            rating={4.8}
            price={189000}
            buyerCount={1200}
            onPressProduct={handleProductPress}
          /> 

          <ProductCard
            imageUrl="https://example.com/product.jpg"
            title="Cream ribbed knit long-sleeve top"
            rating={4.8}
            price={189000}
            buyerCount={1200}
            onPressProduct={handleProductPress}
          /> 

        </View>
        <View className="h-28" />
      </ScrollView>
    </View>
  );
}
