import { View, ScrollView } from 'react-native';
import { useState } from 'react';
import TipsRecommendation from 'components/scan/TipsRecomendation';
import NextStepButton from 'components/scan/NextStepButton';
import TextInputWithLabel from 'components/scan/TextInputwithLabel';
import CustomRadioInput, {CustomRadioButtonType,} from 'components/scan/CustomRadioInput';
import GenerationSteps, { GenerationStep } from 'components/scan/GenerationSteps';
import SessionInfo from 'components/scan/SessionInfo';
import OutfitCard from 'components/scan/OutfitCard';
import ProductCard from 'components/global/ProductCard';
import PhotoPreview from 'components/scan/PhotoPreview';


export default function ScanScreen() {
  const [lookTitle, setLookTitle] = useState('');
  const [selectedCategories, setSelectedCategories] = useState<string[]>([
    'outerwear',
  ]);

  const handleProductPress = () => {
    console.log('product pressed!');
  };

  const categories: CustomRadioButtonType[] = [
    { id: 'outerwear', value: 'Outerwear', icon: 'shirt-outline' },
    { id: 'footwear', value: 'Footwear', icon: 'footsteps-outline' },
    { id: 'dress', value: 'Dress', icon: 'woman-outline' },
    { id: 'work', value: 'Work', icon: 'briefcase-outline' },
    { id: 'date', value: 'Date', icon: 'heart-outline' },
    { id: 'party', value: 'Party', icon: 'wine-outline' },
  ];

  const steps: GenerationStep[] = [
    {
      id: 1,
      title: 'Creating a prompt',
      description: 'Merged your occasion, style tags, and preferences into an AI prompt.',
      status: 'done',
      timestamp: 'Just now',
    },
    {
      id: 2,
      title: 'Submitting the prompt',
      description: 'Sent the formatted prompt securely to the Stylo AI model.',
      status: 'done',
      timestamp: 'Just now',
    },
    {
      id: 3,
      title: 'Getting result from prompt',
      description: 'Received your outfit idea and item breakdown from the model.',
      status: 'done',
      timestamp: 'Just now',
    },
    {
      id: 4,
      title: 'Getting data for scraping',
      description: 'Converted each outfit item into search-ready product keywords.',
      status: 'done',
      timestamp: 'Just now',
    },
    {
      id: 5,
      title: 'Requesting data in scrap queue',
      description: 'Queued product searches with partnered marketplaces.',
      status: 'done',
      timestamp: 'Just now',
    },
    {
      id: 6,
      title: 'Getting the scrap result',
      description: 'Matched outfit items with real products, prices, and ratings.',
      status: 'done',
      timestamp: 'Just now',
    },
    {
      id: 7,
      title: 'Successful generation',
      description: 'Your AI outfit and shoppable items are ready to preview.',
      status: 'ready',
      timestamp: 'Just now',
    },

  
  ];

  return (
    <View className="flex-1 bg-gray-100">
      <ScrollView showsVerticalScrollIndicator={false}>
        <View className='px-6'>
          <PhotoPreview
              onCameraPress={() => {
                console.log('Camera pressed');
              }}
              onGalleryPress={() => {
                console.log('Gallery pressed');
              }}
              onHelpPress={() => {
                console.log('Help pressed');
              }}
            />
          </View>
        <View className="p-6">
          <TipsRecommendation />
        </View>

        <View className="px-6">
          <TextInputWithLabel
            title="Title this look"
            description="Add a short name so you can find it easily later."
            label="Look title"
            placeholder='e.g. "Friday date night"'
            value={lookTitle}
            onChangeText={setLookTitle}
          />
        </View>

        <View className='px-6'>
          <CustomRadioInput
            title="What should we focus on"
            description="Pick one or more categories to guide the recommendations"
            label="Categories"
            items={categories}
            value={selectedCategories}
            onValueChange={setSelectedCategories}
            multiSelect
          />
        </View>

        <View className='p-6'>
          <GenerationSteps data={steps}/>
        </View>

        <View className='px-6'>
          <SessionInfo
            sessionId="#STY-2406-18"
            totalSteps={7}
            completedSteps={7}
            elapsedTime="3.2 seconds"
            status="completed"
          />
        </View>

        <View className='px-6'>
          <OutfitCard
            title="Soft neutral date night look"
            subtitle="Generated by Style AI · Look 1 of 5"
            description="Cream knit top with tailored black trousers, layered with a light trench and clean white sneakers. Balanced, polished, and comfortable for an indoor dinner date."
            onSaveOutfit={() => {
              console.log('Save outfit');
            }}
            onSaveItems={() => {
              console.log('Save single items');
            }}
          />

        </View>

        <View className="px-6">
          <ProductCard
            imageUrl="https://example.com/product.jpg"
            title="Cream ribbed knit long-sleeve top"
            rating={4.8}
            price={189000}
            buyerCount={1200}
            onPressProduct={handleProductPress}
          />
      </View>
      </ScrollView>

      <NextStepButton
        promptText="Next: describe your occasion and style"
        buttonText="Continue"
        buttonIcon="sparkles"
        onPress={() => console.log(selectedCategories)}
      />
    </View>
  );
}
