import React, { useRef, useState } from 'react';
import {
  View,
  Text,
  Image,
  ScrollView,
  TouchableOpacity,
  Dimensions,
  StatusBar,
  Platform,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import ButtonGlobal from 'components/global/ButtonGlobal';

const { width } = Dimensions.get('window');
const IMAGE_HEIGHT = 340;

// ─── Types ────────────────────────────────────────────────────────────────────

interface OutfitLook {
  id: string;
  label: string; // e.g. "Look 1 · Front"
  imageUrl: string;
  isAiGenerated?: boolean;
}

interface OutfitTag {
  id: string;
  label: string;
  icon?: keyof typeof Ionicons.glyphMap;
}

interface OutfitProduct {
  id: string;
  imageUrl: string;
  title: string;
  shopName: string;
  price: number;          // in IDR
  rating?: number;
  reviewCount?: number;
  productUrl: string;
}

interface OutfitDetail {
  id: string;
  title: string;
  generatedBy: string;
  style: string;          // e.g. "Smart casual"
  date: string;
  summary: string;
  contextTags: OutfitTag[];
  looks: OutfitLook[];
  products: OutfitProduct[];
}

// ─── Mock data (replace with real API / route params) ─────────────────────────

const MOCK_OUTFIT: OutfitDetail = {
  id: '1',
  title: 'Soft date-night neutrals',
  generatedBy: 'Dinner date · Generated by Stylo AI',
  style: 'Smart casual',
  date: 'Today, 8:12 PM',
  summary:
    'Soft neutral layers keep this date-night look elevated but relaxed. The fitted top balances wide-leg trousers, while minimal heels and a structured bag add polish without feeling too formal.',
  contextTags: [
    { id: '1', label: '24b0C evening', icon: 'thermometer-outline' },
    { id: '2', label: 'Indoor restaurant', icon: 'people-outline' },
    { id: '3', label: 'Full look', icon: 'sparkles-outline' },
  ],
  looks: [
    {
      id: '1',
      label: 'Look 1 · Front',
      imageUrl: 'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=400',
      isAiGenerated: true,
    },
    {
      id: '2',
      label: 'Look 2 · Side',
      imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400',
      isAiGenerated: true,
    },
  ],
  products: [
    {
      id: 'p1',
      imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4b4645?w=200',
      title: 'Cream wrap blouse with subtle drape',
      shopName: 'Minimal Studio',
      price: 329000,
      rating: 4.8,
      reviewCount: 1200,
      productUrl: 'https://shopee.co.id',
    },
    {
      id: 'p2',
      imageUrl: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=200',
      title: 'High-waist beige wide-leg trousers',
      shopName: 'Tailored Co.',
      price: 415000,
      rating: 4.9,
      reviewCount: 890,
      productUrl: 'https://shopee.co.id',
    },
    {
      id: 'p3',
      imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=200',
      title: 'Nude low-heel strappy sandals',
      shopName: 'Ease Footwear',
      price: 280000,
      rating: 4.7,
      reviewCount: 640,
      productUrl: 'https://shopee.co.id',
    },
    {
      id: 'p4',
      imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=200',
      title: 'Beige mini shoulder bag',
      shopName: 'Daily Carry',
      price: 242000,
      rating: 4.6,
      reviewCount: 410,
      productUrl: 'https://shopee.co.id',
    },
  ],
};

// ─── Sub-components ───────────────────────────────────────────────────────────

/** Pill badge (style tag at top) */
function StyleBadge({ label }: { label: string }) {
  return (
    <View className="flex-row items-center bg-[#7C3AED] px-3 py-1.5 rounded-full self-start gap-1.5">
      <Ionicons name="sparkles" size={12} color="#fff" />
      <Text className="text-xs font-semibold text-white">{label}</Text>
    </View>
  );
}

/** Context tag pill (inside outfit summary) */
function ContextTag({ icon, label }: { icon?: keyof typeof Ionicons.glyphMap; label: string }) {
  return (
    <View className="flex-row items-center bg-gray-100 px-2.5 py-1.5 rounded-full gap-1">
      {icon && <Ionicons name={icon} size={12} color="#6b7280" />}
      <Text className="text-xs text-gray-600 font-medium">{label}</Text>
    </View>
  );
}

/** Single product row */
function ProductRow({ product }: { product: OutfitProduct }) {
  const formatPrice = (p: number) =>
    `IDR ${p.toLocaleString('id-ID')}`;

  const formatCount = (n: number) =>
    n >= 1000 ? `${(n / 1000).toFixed(1)}k` : `${n}`;

  return (
    <View className="bg-white rounded-2xl mb-3 p-3">
      <View className="flex-row gap-3 items-center">
        {/* Thumbnail */}
        <Image
          source={{ uri: product.imageUrl }}
          className="w-20 h-20 rounded-xl bg-gray-100"
          resizeMode="cover"
        />

        {/* Info */}
        <View className="flex-1">
          <Text className="text-sm font-semibold text-gray-900 mb-0.5" numberOfLines={2}>
            {product.title}
          </Text>
          <Text className="text-xs text-gray-400 mb-1">{product.shopName}</Text>

          {/* Rating row */}
          {product.rating !== undefined && (
            <View className="flex-row items-center gap-1 mb-1.5">
              <Ionicons name="star" size={12} color="#fbbf24" />
              <Text className="text-xs font-semibold text-gray-700">
                {product.rating.toFixed(1)}
              </Text>
              {product.reviewCount !== undefined && (
                <Text className="text-xs text-gray-400">
                  · {formatCount(product.reviewCount)} reviews
                </Text>
              )}
            </View>
          )}

          <Text className="text-base font-bold text-gray-900">
            {formatPrice(product.price)}
          </Text>
        </View>

        {/* CTA */}
        <View className="items-end gap-2">
          <ButtonGlobal
            title="View product"
            color="secondary"
            onPress={() => { /* open productUrl */ }}
            size="xs"
          />
          <Text className="text-xs text-[#7C3AED] font-medium">Save item only</Text>
        </View>
      </View>
    </View>
  );
}

export default function OutfitDetailScreen() {

  const outfit = MOCK_OUTFIT;

  const scrollViewRef = useRef<ScrollView>(null);
  const [activeIndex, setActiveIndex] = useState(0);
  const [summaryExpanded, setSummaryExpanded] = useState(false);

  const handleImageScroll = (e: any) => {
    const x = e.nativeEvent.contentOffset.x;
    setActiveIndex(Math.round(x / width));
  };

  return (
    <View className="flex-1 bg-[#F5F5F7]">
      <StatusBar barStyle="dark-content" />

      {/* ── Header bar ── */}
      <View
        className="flex-row items-center px-4 bg-white border-b border-gray-100"
        style={{ paddingTop: Platform.OS === 'ios' ? 52 : 16, paddingBottom: 12 }}
      >
        <TouchableOpacity
          onPress={() => router.back()}
          className="w-9 h-9 rounded-full bg-gray-100 items-center justify-center mr-3"
          hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
        >
          <Ionicons name="chevron-back" size={20} color="#111" />
        </TouchableOpacity>

        <View className="flex-1">
          <Text className="text-base font-bold text-gray-900" numberOfLines={1}>
            {outfit.title}
          </Text>
          <Text className="text-xs text-gray-400 mt-0.5" numberOfLines={1}>
            {outfit.generatedBy}
          </Text>
        </View>

        <TouchableOpacity
          className="w-9 h-9 rounded-full bg-gray-100 items-center justify-center ml-2"
          hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
        >
          <Ionicons name="share-social-outline" size={18} color="#111" />
        </TouchableOpacity>
      </View>

      {/* ── Scrollable body ── */}
      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{ paddingBottom: 120 }}
      >
        {/* Style badge + date */}
        <View className="flex-row items-center justify-between px-4 pt-4 pb-2 bg-white">
          <StyleBadge label={outfit.style} />
          <View className="flex-row items-center gap-1">
            <Ionicons name="time-outline" size={13} color="#9ca3af" />
            <Text className="text-xs text-gray-400">{outfit.date}</Text>
          </View>
        </View>

        {/* ── Image Carousel ── */}
        <View className="bg-white pb-4">
          <View className="mx-4 bg-gray-100 rounded-2xl overflow-hidden">
            <ScrollView
              ref={scrollViewRef}
              horizontal
              pagingEnabled
              showsHorizontalScrollIndicator={false}
              onScroll={handleImageScroll}
              scrollEventThrottle={16}
            >
              {outfit.looks.map((look) => (
                <View key={look.id} style={{ width: width - 32 }}>
                  <Image
                    source={{ uri: look.imageUrl }}
                    style={{ width: '100%', height: IMAGE_HEIGHT }}
                    resizeMode="cover"
                  />
                  {/* Look label */}
                  <View className="absolute bottom-3 left-3 flex-row items-center gap-1.5">
                    <View className="bg-black/40 px-2.5 py-1 rounded-full flex-row items-center gap-1">
                      <Text className="text-xs text-white font-medium">{look.label}</Text>
                      {look.isAiGenerated && (
                        <View className="flex-row items-center gap-0.5">
                          <Text className="text-gray-300 text-xs">·</Text>
                          <Ionicons name="sparkles" size={10} color="#c4b5fd" />
                          <Text className="text-xs text-purple-200 font-medium">AI generated</Text>
                        </View>
                      )}
                    </View>
                  </View>
                </View>
              ))}
            </ScrollView>

            {/* Dots */}
            <View className="flex-row justify-center gap-2 py-3">
              {outfit.looks.map((_, i) => (
                <View
                  key={i}
                  style={{
                    width: i === activeIndex ? 24 : 6,
                    height: 6,
                    borderRadius: 3,
                    backgroundColor: i === activeIndex ? '#7C3AED' : '#d1d5db',
                  }}
                />
              ))}
            </View>
          </View>
        </View>

        {/* ── Outfit Summary ── */}
        <View className="mx-4 mt-3 bg-white rounded-2xl p-4">
          <View className="flex-row items-center justify-between mb-2">
            <Text className="text-base font-bold text-gray-900">Outfit summary</Text>
            <TouchableOpacity
              className="flex-row items-center gap-1"
              onPress={() => {/* open AI notes */ }}
            >
              <Ionicons name="sparkles-outline" size={14} color="#7C3AED" />
              <Text className="text-xs text-[#7C3AED] font-medium">AI style notes</Text>
            </TouchableOpacity>
          </View>

          <Text
            className="text-sm text-gray-500 leading-5"
            numberOfLines={summaryExpanded ? undefined : 3}
          >
            {outfit.summary}
          </Text>

          {outfit.summary.length > 120 && (
            <TouchableOpacity onPress={() => setSummaryExpanded(!summaryExpanded)} className="mt-1">
              <Text className="text-xs text-[#7C3AED] font-semibold">
                {summaryExpanded ? 'Show less' : 'Read more'}
              </Text>
            </TouchableOpacity>
          )}

          {/* Context tags */}
          <View className="flex-row flex-wrap gap-2 mt-3">
            {outfit.contextTags.map((tag) => (
              <ContextTag key={tag.id} icon={tag.icon} label={tag.label} />
            ))}
          </View>
        </View>

        {/* ── Action buttons ── */}
        <View className="flex-row gap-3 mx-4 mt-3">
          <TouchableOpacity
            className="flex-1 flex-row items-center justify-center gap-2 bg-white border border-gray-200 rounded-xl py-3"
            activeOpacity={0.8}
          >
            <Ionicons name="bookmark-outline" size={16} color="#7C3AED" />
            <Text className="text-sm font-semibold text-[#7C3AED]">Save outfit</Text>
          </TouchableOpacity>

          <TouchableOpacity
            className="flex-1 flex-row items-center justify-center gap-2 bg-white border border-gray-200 rounded-xl py-3"
            activeOpacity={0.8}
          >
            <Ionicons name="add-circle-outline" size={16} color="#7C3AED" />
            <Text className="text-sm font-semibold text-[#7C3AED]">Single items</Text>
          </TouchableOpacity>
        </View>

        <Text className="text-xs text-gray-400 mx-4 mt-2">
          Save this full look to Saved looks, or bookmark individual pieces to your single items.
        </Text>

        {/* ── Products ── */}
        <View className="mx-4 mt-5">
          <View className="flex-row items-center justify-between mb-3">
            <Text className="text-base font-bold text-gray-900">Products from this look</Text>
            <View className="flex-row items-center gap-1">
              <Image
                source={{ uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Shopee_logo.svg/512px-Shopee_logo.svg.png' }}
                className="w-4 h-4"
                resizeMode="contain"
              />
              <Text className="text-xs text-gray-400">Linked via Shopee</Text>
            </View>
          </View>

          {outfit.products.map((product) => (
            <ProductRow key={product.id} product={product} />
          ))}
        </View>
      </ScrollView>

      {/* ── Sticky bottom CTA ── */}
      <View
        className="absolute bottom-0 left-0 right-0 bg-white border-t border-gray-100 px-4"
        style={{ paddingBottom: Platform.OS === 'ios' ? 34 : 16, paddingTop: 12 }}
      >
        <TouchableOpacity
          className="flex-row items-center justify-center gap-2 bg-[#EE4D2D] rounded-2xl py-3.5"
          activeOpacity={0.85}
        >
          <Ionicons name="cart-outline" size={18} color="#fff" />
          <Text className="text-sm font-bold text-white">Checkout on Shopee</Text>
        </TouchableOpacity>
        <Text className="text-xs text-center text-gray-400 mt-2">
          Buy full look · {outfit.products.length} items
        </Text>
      </View>
    </View>
  );
}